import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full w-full text-gray-900 dark:text-gray-100">
      <body className="h-full w-full">
        {children}
      </body>
    </html>
  );
}
